# Configuration for the GitHub Actions labeler
# Labels by affected paths

core:
 - any: src/**/core/*
blocks:
 - any: src/**/block/*
items:
 - any: src/**/item/*
entities:
 - any: src/**/entity/*
tile-entities:
 - any: src/**/tileentity/*
networking:
 - any: src/**/network/*
particles:
 - any: src/**/particle/*
rituals:
 - any: src/**/ritual/*
