# Configuration for the GitHub Actions labeler
# Labels by affected paths

core:
 - any: ['src/**/core/*']
blocks:
 - any: ['src/**/block/*']
item:
 - any: ['src/**/item/*']
entities:
 - any: ['src/**/entity/*']
tile-entities:
 - any: ['src/**/tileentity/*']
network:
 - any: ['src/**/network/*']
particle:
 - any: ['src/**/particle/*']
ritual:
 - any: ['src/**/ritual/*']
